name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    name: Tests (${{ matrix.dependency }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependency: [cpu, gpu]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements-${{ matrix.dependency }}.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-${{ matrix.dependency }}.txt

      - name: Run tests
        env:
          PYTHONWARNINGS: default
        run: |
          pytest
